### ISSUE TITLE
Can't send an attachment after updating to Roundcube 1.3.3

### ISSUE THREAD

**Issue by xetorixik** [mail-in-a-box/mailinabox#1290]
I can't send an attachment with Roundcube after updating to Roundcube 1.3.3 (Mail in a box v 0.25).

Reproduce: Attach a file, file is attached, sending mail, after verifying with sent folder and the receiver, no attachment is ever sent.

Sending attachments with Outlook, Nine, Thunderbird etc via the Mail in a box server woks fine.
Can someone verify this?

**Comment by JoshData** [comment]
It works for me. Can you provide any other info, like anything odd on the browser developer console?

**Comment by paradoxbound** [comment]
Same issue tested on OSX 10.13.1 with both Firefox 57 and Chrome 62. Attachments show as attached but do not arrive the other end. Happy to post log snippets if you tell me where to look.

**Comment by tynie** [comment]
Same issue here. Tested on Windows 10 1607 with Chrome Version 62.0.3202.94.

**Comment by rverst** [comment]
Same here, with Firefox 57.0 on Windows 10 and with Safari 11.0.1 (13604.3.5) on MacOS 10.13.1 (17B48) as well.
Console is clean, no errors. Attachment is postet to the server as expected. 
No errors in 
* /var/log/mail.err
* /var/log/roundcubemail/errors

mail.log and roundcubemail/sendmail seems to be normal.

**Comment by yoannmoinet** [comment]
Not sure if this is related or not, but there are other occurences of this.
- https://github.com/roundcube/roundcubemail/issues/6063
- https://discourse.mailinabox.email/t/roundcube-attachments/2644

And I have the same issue. Attachment uploads and gets attached, but nothing gets to the other end.

**Comment by yoannmoinet** [comment]
Ok, I got it to work.

First locate the roundcube config file `/usr/local/lib/roundcubemail/config/config.inc.php` for me.
Then, be sure that the folder set in `$config['temp_dir'] = '/tmp/roundcubemail/';` exists.
And make it writable by the `www-data` group.

```
mkdir /tmp/roundcubemail
sudo chown -R www-data /tmp/roundcubemail/
sudo chmod -R g+rwX /tmp/roundcubemail/
```

And voilà, everything is fine now.

**Comment by JimZAH** [comment]
Hi All,

Can confirm I also had this issue. Followed @yoannmoinet instructions and all is working again!

**Comment by tynie** [comment]
That works!

**Comment by xetorixik** [comment]
Upgrading Mail-in-a-Box resolves this problem.

As can be seen at: https://mailinabox.email/maintenance.html

> curl -s https://mailinabox.email/setup.sh | sudo bash

Just like with an upgrade or reinstalling the system.

It basically executes the same code as the solution of @yoannmoinet as seen in the code here:

https://github.com/mail-in-a-box/mailinabox/blob/5f14eca67fce89fb487bfc5511d621b19b7dcc40/setup/webmail.sh

**Comment by paradoxbound** [comment]
I can confirm @yoannmoinet solution worked for me. However, running setup.sh did not.

**Comment by just4t** [comment]
@paradoxbound  Please, reboot your server and check if the _/tmp/roundcubemail/_ folder is still there. If _/tmp/roundcubemail/_ folder doesn't survive after a server reboot then, the reported issue is not yet solved.

**Comment by paradoxbound** [comment]
OK so it doesn't survive reboot but to be honest at this point I would rather have to re-run the commands on reboot than not be able to send attachments. At least at this point we know that it is a problem with vars and tmp dirs. If I get time I will start looking through the code but my time is limited.

**Comment by just4t** [comment]
Try editing the file _/usr/local/lib/roundcubemail/config/config.inc.php_  by going from $_config['temp_dir'] = '/tmp/roundcubemail/';_ to _$config['temp_dir'] = '/tmp/';_ . Doesn't solve the issue, too but may help till final solution will be provided.

**Comment by paradoxbound** [comment]
Not happy about dumping my users possibly sensitive attachments into a world readable /tmp. I would say that /var/tmp/roundcube would make sense and fit with the FSH.
https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#vartmpTemporaryFilesPreservedBetwee

**Comment by just4t** [comment]
Yes! Much better temp. patch.

**Comment by paradoxbound** [comment]
Just to confirm, works with "/var/tmp/roundcube" and directory survives a reboot. looks like the file is only there while the email is in draft form. However if you cancel the draft after attachment, the attachment remains. This maybe an issue on busy mail servers.

**Comment by xetorixik** [comment]
@JoshData Apparently more users are bothered by #1290.
Is a structural solution possible available? For example via the setup(.sh).

@paradoxbound Running setup.sh works fine here, but after a reboot the problem is back. 
So you're right. Hopefully Josh has a permanent solution.

**Comment by zoof** [comment]
I had delayed upgrading because I read about this issue but did so after seeing the @yoannmoinet fix.  It worked fine but now attachments are no longer working.  I assume that the directory I created got wiped or its permissions changed?  I'm firewalled right now so I can't get online to redo the fix but something ought to be done to make the fix permanent.

**Comment by just4t** [comment]
@zoof  See: https://discourse.mailinabox.email/t/roundcube-attachments/2644/13

**Comment by zoof** [comment]
Thank you -- it worked!

**Comment by JoshData** [comment]
Fixed in #1302.

**Comment by OmgImAlexis** [comment]
@JoshData any idea on the ETA for the next release?

**Comment by wyllieone** [comment]
Hi, just tried this $config['temp_dir'] = '/tmp/roundcubemail/';  fix with both the /roundcubemail & /tmp extensions but can't send mail attachments. I am using the lates MIAB v0.43. have updated all the systems software too but still won't work? Only thing in red on the MIAB's systems checks is "The SSH server on this machine permits password-based login" would that stop attachments from going through? Any ideas on this? Thanks!
