### ISSUE TITLE
Cron error message from mailinabox-ssl-cleanup

### ISSUE THREAD

**Issue by tstanczak** [mail-in-a-box/mailinabox#2479]
After installing v71 my admin has received this mail:

/etc/cron.daily/mailinabox-ssl-cleanup:
mv: cannot stat '/home/user-data/ssl/*-+([0-9])-+([0-9a-f]).pem': No such file or directory
run-parts: /etc/cron.daily/mailinabox-ssl-cleanup exited with return code 1

Probably it should be first checked if there is at least one file matching the pattern in $STORAGE_ROOT/ssl

**Comment by tstanczak** [comment]
There are several files there, like lets encrypt directory, private key, link to the certificate. Then my own certificate I copied into the directory and linked to ssl_certificate.pem - this is the one MIAB uses for my domain. And one selfsigned created during the original installation. None of them matches the pattern used during the cleanup. 

This is why I suggested checking if files matching the pattern exist before trying to move them away. Actually looking at the script one could think that this is what would happen - there is a for loop inside, so without files the loop shouldn't be entered at all. But it is.

I have already fixed it in my installation, I'll make a PR.

**Comment by tstanczak** [comment]
PR is there.

**Comment by dms00** [comment]
While I still don't understand why you have no files to match the for-loop's glob, I believe the correct way to fix this would be to set the nullglob option, `shopt -s nullglob`. Discussed here: https://stackoverflow.com/questions/26255799/how-to-skip-the-for-loop-when-there-are-no-matching-files

**Comment by tstanczak** [comment]
Thank you for the hint. Being a software engineer but not an expert in shell it never came into my mind that there might be such an option.
